# query_app/urls.py

from django.urls import path, include
from rest_framework import routers
from . import views

# 1. Create a router for the DRF ViewSet
router = routers.DefaultRouter()

# 2. Register your QueryTemplateViewSet with the router
# This tells the router to create URLs for the 'templates' API endpoint
router.register(r'templates', views.QueryTemplateViewSet)


# 3. Define the final URL patterns
urlpatterns = [
    # This path serves the main HTML page at the root URL (e.g., /query/)
    path('', views.query_builder_page, name='query_builder_page'),

    # This is the path for your original API that executes the SQL query
    path('api/query/', views.query_builder_api, name='query_builder_api'),
    
    # This includes all the URLs automatically generated by the DRF router.
    # It will create the paths for your new templates API under '/api/'
    path('api/', include(router.urls)),
]